//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ModelTutorBooking", "FK_tblTutorCourse_tblCourse", "tblCourse", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ModelTutorBooking.tblCourse), "tblTutorCourse", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ModelTutorBooking.tblTutorCourse), true)]
[assembly: EdmRelationshipAttribute("ModelTutorBooking", "FK_tblSchedule_tblTutor", "tblTutor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ModelTutorBooking.tblTutor), "tblSchedule", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ModelTutorBooking.tblSchedule), true)]
[assembly: EdmRelationshipAttribute("ModelTutorBooking", "FK_tblTutorCourse_tblTutor", "tblTutor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ModelTutorBooking.tblTutor), "tblTutorCourse", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ModelTutorBooking.tblTutorCourse), true)]
[assembly: EdmRelationshipAttribute("ModelTutorBooking", "FK_tblBooking_tblCourse", "tblCourse", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ModelTutorBooking.tblCourse), "tblBooking", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ModelTutorBooking.tblBooking), true)]
[assembly: EdmRelationshipAttribute("ModelTutorBooking", "FK_tblBooking_tblStudent", "tblStudent", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ModelTutorBooking.tblStudent), "tblBooking", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ModelTutorBooking.tblBooking), true)]
[assembly: EdmRelationshipAttribute("ModelTutorBooking", "FK_tblBooking_tblTutor", "tblTutor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ModelTutorBooking.tblTutor), "tblBooking", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ModelTutorBooking.tblBooking), true)]
[assembly: EdmRelationshipAttribute("ModelTutorBooking", "FK_tblRating_tblStudent", "tblStudent", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ModelTutorBooking.tblStudent), "tblRating", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ModelTutorBooking.tblRating), true)]
[assembly: EdmRelationshipAttribute("ModelTutorBooking", "FK_tblRating_tblTutor", "tblTutor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ModelTutorBooking.tblTutor), "tblRating", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ModelTutorBooking.tblRating), true)]

#endregion

namespace ModelTutorBooking
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ModelTutor : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ModelTutor object using the connection string found in the 'ModelTutor' section of the application configuration file.
        /// </summary>
        public ModelTutor() : base("name=ModelTutor", "ModelTutor")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ModelTutor object.
        /// </summary>
        public ModelTutor(string connectionString) : base(connectionString, "ModelTutor")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ModelTutor object.
        /// </summary>
        public ModelTutor(EntityConnection connection) : base(connection, "ModelTutor")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblCourse> tblCourses
        {
            get
            {
                if ((_tblCourses == null))
                {
                    _tblCourses = base.CreateObjectSet<tblCourse>("tblCourses");
                }
                return _tblCourses;
            }
        }
        private ObjectSet<tblCourse> _tblCourses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblSchedule> tblSchedules
        {
            get
            {
                if ((_tblSchedules == null))
                {
                    _tblSchedules = base.CreateObjectSet<tblSchedule>("tblSchedules");
                }
                return _tblSchedules;
            }
        }
        private ObjectSet<tblSchedule> _tblSchedules;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblStudent> tblStudents
        {
            get
            {
                if ((_tblStudents == null))
                {
                    _tblStudents = base.CreateObjectSet<tblStudent>("tblStudents");
                }
                return _tblStudents;
            }
        }
        private ObjectSet<tblStudent> _tblStudents;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblTutor> tblTutors
        {
            get
            {
                if ((_tblTutors == null))
                {
                    _tblTutors = base.CreateObjectSet<tblTutor>("tblTutors");
                }
                return _tblTutors;
            }
        }
        private ObjectSet<tblTutor> _tblTutors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblTutorCourse> tblTutorCourses
        {
            get
            {
                if ((_tblTutorCourses == null))
                {
                    _tblTutorCourses = base.CreateObjectSet<tblTutorCourse>("tblTutorCourses");
                }
                return _tblTutorCourses;
            }
        }
        private ObjectSet<tblTutorCourse> _tblTutorCourses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblAdmin> tblAdmins
        {
            get
            {
                if ((_tblAdmins == null))
                {
                    _tblAdmins = base.CreateObjectSet<tblAdmin>("tblAdmins");
                }
                return _tblAdmins;
            }
        }
        private ObjectSet<tblAdmin> _tblAdmins;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblBooking> tblBookings
        {
            get
            {
                if ((_tblBookings == null))
                {
                    _tblBookings = base.CreateObjectSet<tblBooking>("tblBookings");
                }
                return _tblBookings;
            }
        }
        private ObjectSet<tblBooking> _tblBookings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblRating> tblRatings
        {
            get
            {
                if ((_tblRatings == null))
                {
                    _tblRatings = base.CreateObjectSet<tblRating>("tblRatings");
                }
                return _tblRatings;
            }
        }
        private ObjectSet<tblRating> _tblRatings;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblCourses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblCourses(tblCourse tblCourse)
        {
            base.AddObject("tblCourses", tblCourse);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblSchedules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblSchedules(tblSchedule tblSchedule)
        {
            base.AddObject("tblSchedules", tblSchedule);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblStudents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblStudents(tblStudent tblStudent)
        {
            base.AddObject("tblStudents", tblStudent);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblTutors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblTutors(tblTutor tblTutor)
        {
            base.AddObject("tblTutors", tblTutor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblTutorCourses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblTutorCourses(tblTutorCourse tblTutorCourse)
        {
            base.AddObject("tblTutorCourses", tblTutorCourse);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblAdmins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblAdmins(tblAdmin tblAdmin)
        {
            base.AddObject("tblAdmins", tblAdmin);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblBookings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblBookings(tblBooking tblBooking)
        {
            base.AddObject("tblBookings", tblBooking);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblRatings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblRatings(tblRating tblRating)
        {
            base.AddObject("tblRatings", tblRating);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelTutorBooking", Name="tblAdmin")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblAdmin : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblAdmin object.
        /// </summary>
        /// <param name="adminId">Initial value of the AdminId property.</param>
        public static tblAdmin CreatetblAdmin(global::System.Int32 adminId)
        {
            tblAdmin tblAdmin = new tblAdmin();
            tblAdmin.AdminId = adminId;
            return tblAdmin;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AdminId
        {
            get
            {
                return _AdminId;
            }
            set
            {
                if (_AdminId != value)
                {
                    OnAdminIdChanging(value);
                    ReportPropertyChanging("AdminId");
                    _AdminId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AdminId");
                    OnAdminIdChanged();
                }
            }
        }
        private global::System.Int32 _AdminId;
        partial void OnAdminIdChanging(global::System.Int32 value);
        partial void OnAdminIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelTutorBooking", Name="tblBooking")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblBooking : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblBooking object.
        /// </summary>
        /// <param name="bookingId">Initial value of the BookingId property.</param>
        /// <param name="tutorId">Initial value of the TutorId property.</param>
        /// <param name="studentId">Initial value of the StudentId property.</param>
        /// <param name="dateOfBooking">Initial value of the DateOfBooking property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="timeOfBooking">Initial value of the TimeOfBooking property.</param>
        /// <param name="courseId">Initial value of the CourseId property.</param>
        public static tblBooking CreatetblBooking(global::System.Int32 bookingId, global::System.Int32 tutorId, global::System.Int32 studentId, global::System.DateTime dateOfBooking, global::System.String description, global::System.String timeOfBooking, global::System.Int32 courseId)
        {
            tblBooking tblBooking = new tblBooking();
            tblBooking.BookingId = bookingId;
            tblBooking.TutorId = tutorId;
            tblBooking.StudentId = studentId;
            tblBooking.DateOfBooking = dateOfBooking;
            tblBooking.Description = description;
            tblBooking.TimeOfBooking = timeOfBooking;
            tblBooking.CourseId = courseId;
            return tblBooking;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BookingId
        {
            get
            {
                return _BookingId;
            }
            set
            {
                if (_BookingId != value)
                {
                    OnBookingIdChanging(value);
                    ReportPropertyChanging("BookingId");
                    _BookingId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BookingId");
                    OnBookingIdChanged();
                }
            }
        }
        private global::System.Int32 _BookingId;
        partial void OnBookingIdChanging(global::System.Int32 value);
        partial void OnBookingIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TutorId
        {
            get
            {
                return _TutorId;
            }
            set
            {
                OnTutorIdChanging(value);
                ReportPropertyChanging("TutorId");
                _TutorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TutorId");
                OnTutorIdChanged();
            }
        }
        private global::System.Int32 _TutorId;
        partial void OnTutorIdChanging(global::System.Int32 value);
        partial void OnTutorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StudentId
        {
            get
            {
                return _StudentId;
            }
            set
            {
                OnStudentIdChanging(value);
                ReportPropertyChanging("StudentId");
                _StudentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StudentId");
                OnStudentIdChanged();
            }
        }
        private global::System.Int32 _StudentId;
        partial void OnStudentIdChanging(global::System.Int32 value);
        partial void OnStudentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateOfBooking
        {
            get
            {
                return _DateOfBooking;
            }
            set
            {
                OnDateOfBookingChanging(value);
                ReportPropertyChanging("DateOfBooking");
                _DateOfBooking = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfBooking");
                OnDateOfBookingChanged();
            }
        }
        private global::System.DateTime _DateOfBooking;
        partial void OnDateOfBookingChanging(global::System.DateTime value);
        partial void OnDateOfBookingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TimeOfBooking
        {
            get
            {
                return _TimeOfBooking;
            }
            set
            {
                OnTimeOfBookingChanging(value);
                ReportPropertyChanging("TimeOfBooking");
                _TimeOfBooking = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TimeOfBooking");
                OnTimeOfBookingChanged();
            }
        }
        private global::System.String _TimeOfBooking;
        partial void OnTimeOfBookingChanging(global::System.String value);
        partial void OnTimeOfBookingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CourseId
        {
            get
            {
                return _CourseId;
            }
            set
            {
                OnCourseIdChanging(value);
                ReportPropertyChanging("CourseId");
                _CourseId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CourseId");
                OnCourseIdChanged();
            }
        }
        private global::System.Int32 _CourseId;
        partial void OnCourseIdChanging(global::System.Int32 value);
        partial void OnCourseIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelTutorBooking", "FK_tblBooking_tblCourse", "tblCourse")]
        public tblCourse tblCourse
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCourse>("ModelTutorBooking.FK_tblBooking_tblCourse", "tblCourse").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCourse>("ModelTutorBooking.FK_tblBooking_tblCourse", "tblCourse").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblCourse> tblCourseReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCourse>("ModelTutorBooking.FK_tblBooking_tblCourse", "tblCourse");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblCourse>("ModelTutorBooking.FK_tblBooking_tblCourse", "tblCourse", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelTutorBooking", "FK_tblBooking_tblStudent", "tblStudent")]
        public tblStudent tblStudent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblStudent>("ModelTutorBooking.FK_tblBooking_tblStudent", "tblStudent").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblStudent>("ModelTutorBooking.FK_tblBooking_tblStudent", "tblStudent").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblStudent> tblStudentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblStudent>("ModelTutorBooking.FK_tblBooking_tblStudent", "tblStudent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblStudent>("ModelTutorBooking.FK_tblBooking_tblStudent", "tblStudent", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelTutorBooking", "FK_tblBooking_tblTutor", "tblTutor")]
        public tblTutor tblTutor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblTutor>("ModelTutorBooking.FK_tblBooking_tblTutor", "tblTutor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblTutor>("ModelTutorBooking.FK_tblBooking_tblTutor", "tblTutor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblTutor> tblTutorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblTutor>("ModelTutorBooking.FK_tblBooking_tblTutor", "tblTutor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblTutor>("ModelTutorBooking.FK_tblBooking_tblTutor", "tblTutor", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelTutorBooking", Name="tblCourse")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblCourse : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblCourse object.
        /// </summary>
        /// <param name="courseId">Initial value of the CourseId property.</param>
        public static tblCourse CreatetblCourse(global::System.Int32 courseId)
        {
            tblCourse tblCourse = new tblCourse();
            tblCourse.CourseId = courseId;
            return tblCourse;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CourseId
        {
            get
            {
                return _CourseId;
            }
            set
            {
                if (_CourseId != value)
                {
                    OnCourseIdChanging(value);
                    ReportPropertyChanging("CourseId");
                    _CourseId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CourseId");
                    OnCourseIdChanged();
                }
            }
        }
        private global::System.Int32 _CourseId;
        partial void OnCourseIdChanging(global::System.Int32 value);
        partial void OnCourseIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CourseCode
        {
            get
            {
                return _CourseCode;
            }
            set
            {
                OnCourseCodeChanging(value);
                ReportPropertyChanging("CourseCode");
                _CourseCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CourseCode");
                OnCourseCodeChanged();
            }
        }
        private global::System.String _CourseCode;
        partial void OnCourseCodeChanging(global::System.String value);
        partial void OnCourseCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelTutorBooking", "FK_tblTutorCourse_tblCourse", "tblTutorCourse")]
        public EntityCollection<tblTutorCourse> tblTutorCourses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblTutorCourse>("ModelTutorBooking.FK_tblTutorCourse_tblCourse", "tblTutorCourse");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblTutorCourse>("ModelTutorBooking.FK_tblTutorCourse_tblCourse", "tblTutorCourse", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelTutorBooking", "FK_tblBooking_tblCourse", "tblBooking")]
        public EntityCollection<tblBooking> tblBookings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblBooking>("ModelTutorBooking.FK_tblBooking_tblCourse", "tblBooking");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblBooking>("ModelTutorBooking.FK_tblBooking_tblCourse", "tblBooking", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelTutorBooking", Name="tblRating")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblRating : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblRating object.
        /// </summary>
        /// <param name="ratingId">Initial value of the RatingId property.</param>
        /// <param name="tutorId">Initial value of the TutorId property.</param>
        /// <param name="studentId">Initial value of the StudentId property.</param>
        /// <param name="rate">Initial value of the Rate property.</param>
        public static tblRating CreatetblRating(global::System.Int32 ratingId, global::System.Int32 tutorId, global::System.Int32 studentId, global::System.Int32 rate)
        {
            tblRating tblRating = new tblRating();
            tblRating.RatingId = ratingId;
            tblRating.TutorId = tutorId;
            tblRating.StudentId = studentId;
            tblRating.Rate = rate;
            return tblRating;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RatingId
        {
            get
            {
                return _RatingId;
            }
            set
            {
                if (_RatingId != value)
                {
                    OnRatingIdChanging(value);
                    ReportPropertyChanging("RatingId");
                    _RatingId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RatingId");
                    OnRatingIdChanged();
                }
            }
        }
        private global::System.Int32 _RatingId;
        partial void OnRatingIdChanging(global::System.Int32 value);
        partial void OnRatingIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TutorId
        {
            get
            {
                return _TutorId;
            }
            set
            {
                OnTutorIdChanging(value);
                ReportPropertyChanging("TutorId");
                _TutorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TutorId");
                OnTutorIdChanged();
            }
        }
        private global::System.Int32 _TutorId;
        partial void OnTutorIdChanging(global::System.Int32 value);
        partial void OnTutorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StudentId
        {
            get
            {
                return _StudentId;
            }
            set
            {
                OnStudentIdChanging(value);
                ReportPropertyChanging("StudentId");
                _StudentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StudentId");
                OnStudentIdChanged();
            }
        }
        private global::System.Int32 _StudentId;
        partial void OnStudentIdChanging(global::System.Int32 value);
        partial void OnStudentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Rate
        {
            get
            {
                return _Rate;
            }
            set
            {
                OnRateChanging(value);
                ReportPropertyChanging("Rate");
                _Rate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Rate");
                OnRateChanged();
            }
        }
        private global::System.Int32 _Rate;
        partial void OnRateChanging(global::System.Int32 value);
        partial void OnRateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelTutorBooking", "FK_tblRating_tblStudent", "tblStudent")]
        public tblStudent tblStudent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblStudent>("ModelTutorBooking.FK_tblRating_tblStudent", "tblStudent").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblStudent>("ModelTutorBooking.FK_tblRating_tblStudent", "tblStudent").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblStudent> tblStudentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblStudent>("ModelTutorBooking.FK_tblRating_tblStudent", "tblStudent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblStudent>("ModelTutorBooking.FK_tblRating_tblStudent", "tblStudent", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelTutorBooking", "FK_tblRating_tblTutor", "tblTutor")]
        public tblTutor tblTutor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblTutor>("ModelTutorBooking.FK_tblRating_tblTutor", "tblTutor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblTutor>("ModelTutorBooking.FK_tblRating_tblTutor", "tblTutor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblTutor> tblTutorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblTutor>("ModelTutorBooking.FK_tblRating_tblTutor", "tblTutor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblTutor>("ModelTutorBooking.FK_tblRating_tblTutor", "tblTutor", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelTutorBooking", Name="tblSchedule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblSchedule : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblSchedule object.
        /// </summary>
        /// <param name="scheduleId">Initial value of the ScheduleId property.</param>
        /// <param name="tutorId">Initial value of the TutorId property.</param>
        public static tblSchedule CreatetblSchedule(global::System.Int32 scheduleId, global::System.Int32 tutorId)
        {
            tblSchedule tblSchedule = new tblSchedule();
            tblSchedule.ScheduleId = scheduleId;
            tblSchedule.TutorId = tutorId;
            return tblSchedule;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ScheduleId
        {
            get
            {
                return _ScheduleId;
            }
            set
            {
                if (_ScheduleId != value)
                {
                    OnScheduleIdChanging(value);
                    ReportPropertyChanging("ScheduleId");
                    _ScheduleId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ScheduleId");
                    OnScheduleIdChanged();
                }
            }
        }
        private global::System.Int32 _ScheduleId;
        partial void OnScheduleIdChanging(global::System.Int32 value);
        partial void OnScheduleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TutorId
        {
            get
            {
                return _TutorId;
            }
            set
            {
                OnTutorIdChanging(value);
                ReportPropertyChanging("TutorId");
                _TutorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TutorId");
                OnTutorIdChanged();
            }
        }
        private global::System.Int32 _TutorId;
        partial void OnTutorIdChanging(global::System.Int32 value);
        partial void OnTutorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mo
        {
            get
            {
                return _Mo;
            }
            set
            {
                OnMoChanging(value);
                ReportPropertyChanging("Mo");
                _Mo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mo");
                OnMoChanged();
            }
        }
        private global::System.String _Mo;
        partial void OnMoChanging(global::System.String value);
        partial void OnMoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tu
        {
            get
            {
                return _Tu;
            }
            set
            {
                OnTuChanging(value);
                ReportPropertyChanging("Tu");
                _Tu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tu");
                OnTuChanged();
            }
        }
        private global::System.String _Tu;
        partial void OnTuChanging(global::System.String value);
        partial void OnTuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String We
        {
            get
            {
                return _We;
            }
            set
            {
                OnWeChanging(value);
                ReportPropertyChanging("We");
                _We = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("We");
                OnWeChanged();
            }
        }
        private global::System.String _We;
        partial void OnWeChanging(global::System.String value);
        partial void OnWeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Th
        {
            get
            {
                return _Th;
            }
            set
            {
                OnThChanging(value);
                ReportPropertyChanging("Th");
                _Th = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Th");
                OnThChanged();
            }
        }
        private global::System.String _Th;
        partial void OnThChanging(global::System.String value);
        partial void OnThChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fr
        {
            get
            {
                return _Fr;
            }
            set
            {
                OnFrChanging(value);
                ReportPropertyChanging("Fr");
                _Fr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Fr");
                OnFrChanged();
            }
        }
        private global::System.String _Fr;
        partial void OnFrChanging(global::System.String value);
        partial void OnFrChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelTutorBooking", "FK_tblSchedule_tblTutor", "tblTutor")]
        public tblTutor tblTutor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblTutor>("ModelTutorBooking.FK_tblSchedule_tblTutor", "tblTutor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblTutor>("ModelTutorBooking.FK_tblSchedule_tblTutor", "tblTutor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblTutor> tblTutorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblTutor>("ModelTutorBooking.FK_tblSchedule_tblTutor", "tblTutor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblTutor>("ModelTutorBooking.FK_tblSchedule_tblTutor", "tblTutor", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelTutorBooking", Name="tblStudent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblStudent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblStudent object.
        /// </summary>
        /// <param name="studentId">Initial value of the StudentId property.</param>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        public static tblStudent CreatetblStudent(global::System.Int32 studentId, global::System.String id, global::System.String name, global::System.String email)
        {
            tblStudent tblStudent = new tblStudent();
            tblStudent.StudentId = studentId;
            tblStudent.Id = id;
            tblStudent.Name = name;
            tblStudent.Email = email;
            return tblStudent;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StudentId
        {
            get
            {
                return _StudentId;
            }
            set
            {
                if (_StudentId != value)
                {
                    OnStudentIdChanging(value);
                    ReportPropertyChanging("StudentId");
                    _StudentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StudentId");
                    OnStudentIdChanged();
                }
            }
        }
        private global::System.Int32 _StudentId;
        partial void OnStudentIdChanging(global::System.Int32 value);
        partial void OnStudentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _Active;
        partial void OnActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnActiveChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelTutorBooking", "FK_tblBooking_tblStudent", "tblBooking")]
        public EntityCollection<tblBooking> tblBookings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblBooking>("ModelTutorBooking.FK_tblBooking_tblStudent", "tblBooking");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblBooking>("ModelTutorBooking.FK_tblBooking_tblStudent", "tblBooking", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelTutorBooking", "FK_tblRating_tblStudent", "tblRating")]
        public EntityCollection<tblRating> tblRatings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblRating>("ModelTutorBooking.FK_tblRating_tblStudent", "tblRating");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblRating>("ModelTutorBooking.FK_tblRating_tblStudent", "tblRating", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelTutorBooking", Name="tblTutor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblTutor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblTutor object.
        /// </summary>
        /// <param name="tutorId">Initial value of the TutorId property.</param>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static tblTutor CreatetblTutor(global::System.Int32 tutorId, global::System.String id, global::System.String name, global::System.String email, global::System.String password)
        {
            tblTutor tblTutor = new tblTutor();
            tblTutor.TutorId = tutorId;
            tblTutor.Id = id;
            tblTutor.Name = name;
            tblTutor.Email = email;
            tblTutor.Password = password;
            return tblTutor;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TutorId
        {
            get
            {
                return _TutorId;
            }
            set
            {
                if (_TutorId != value)
                {
                    OnTutorIdChanging(value);
                    ReportPropertyChanging("TutorId");
                    _TutorId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TutorId");
                    OnTutorIdChanged();
                }
            }
        }
        private global::System.Int32 _TutorId;
        partial void OnTutorIdChanging(global::System.Int32 value);
        partial void OnTutorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _Active;
        partial void OnActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnActiveChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelTutorBooking", "FK_tblSchedule_tblTutor", "tblSchedule")]
        public EntityCollection<tblSchedule> tblSchedules
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblSchedule>("ModelTutorBooking.FK_tblSchedule_tblTutor", "tblSchedule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblSchedule>("ModelTutorBooking.FK_tblSchedule_tblTutor", "tblSchedule", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelTutorBooking", "FK_tblTutorCourse_tblTutor", "tblTutorCourse")]
        public EntityCollection<tblTutorCourse> tblTutorCourses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblTutorCourse>("ModelTutorBooking.FK_tblTutorCourse_tblTutor", "tblTutorCourse");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblTutorCourse>("ModelTutorBooking.FK_tblTutorCourse_tblTutor", "tblTutorCourse", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelTutorBooking", "FK_tblBooking_tblTutor", "tblBooking")]
        public EntityCollection<tblBooking> tblBookings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblBooking>("ModelTutorBooking.FK_tblBooking_tblTutor", "tblBooking");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblBooking>("ModelTutorBooking.FK_tblBooking_tblTutor", "tblBooking", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelTutorBooking", "FK_tblRating_tblTutor", "tblRating")]
        public EntityCollection<tblRating> tblRatings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblRating>("ModelTutorBooking.FK_tblRating_tblTutor", "tblRating");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblRating>("ModelTutorBooking.FK_tblRating_tblTutor", "tblRating", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelTutorBooking", Name="tblTutorCourse")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblTutorCourse : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblTutorCourse object.
        /// </summary>
        /// <param name="tutorCourseId">Initial value of the TutorCourseId property.</param>
        /// <param name="tutorId">Initial value of the TutorId property.</param>
        /// <param name="courseId">Initial value of the CourseId property.</param>
        /// <param name="grade">Initial value of the Grade property.</param>
        public static tblTutorCourse CreatetblTutorCourse(global::System.Int32 tutorCourseId, global::System.Int32 tutorId, global::System.Int32 courseId, global::System.String grade)
        {
            tblTutorCourse tblTutorCourse = new tblTutorCourse();
            tblTutorCourse.TutorCourseId = tutorCourseId;
            tblTutorCourse.TutorId = tutorId;
            tblTutorCourse.CourseId = courseId;
            tblTutorCourse.Grade = grade;
            return tblTutorCourse;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TutorCourseId
        {
            get
            {
                return _TutorCourseId;
            }
            set
            {
                if (_TutorCourseId != value)
                {
                    OnTutorCourseIdChanging(value);
                    ReportPropertyChanging("TutorCourseId");
                    _TutorCourseId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TutorCourseId");
                    OnTutorCourseIdChanged();
                }
            }
        }
        private global::System.Int32 _TutorCourseId;
        partial void OnTutorCourseIdChanging(global::System.Int32 value);
        partial void OnTutorCourseIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TutorId
        {
            get
            {
                return _TutorId;
            }
            set
            {
                OnTutorIdChanging(value);
                ReportPropertyChanging("TutorId");
                _TutorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TutorId");
                OnTutorIdChanged();
            }
        }
        private global::System.Int32 _TutorId;
        partial void OnTutorIdChanging(global::System.Int32 value);
        partial void OnTutorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CourseId
        {
            get
            {
                return _CourseId;
            }
            set
            {
                OnCourseIdChanging(value);
                ReportPropertyChanging("CourseId");
                _CourseId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CourseId");
                OnCourseIdChanged();
            }
        }
        private global::System.Int32 _CourseId;
        partial void OnCourseIdChanging(global::System.Int32 value);
        partial void OnCourseIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Grade
        {
            get
            {
                return _Grade;
            }
            set
            {
                OnGradeChanging(value);
                ReportPropertyChanging("Grade");
                _Grade = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Grade");
                OnGradeChanged();
            }
        }
        private global::System.String _Grade;
        partial void OnGradeChanging(global::System.String value);
        partial void OnGradeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _Active;
        partial void OnActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnActiveChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelTutorBooking", "FK_tblTutorCourse_tblCourse", "tblCourse")]
        public tblCourse tblCourse
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCourse>("ModelTutorBooking.FK_tblTutorCourse_tblCourse", "tblCourse").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCourse>("ModelTutorBooking.FK_tblTutorCourse_tblCourse", "tblCourse").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblCourse> tblCourseReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCourse>("ModelTutorBooking.FK_tblTutorCourse_tblCourse", "tblCourse");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblCourse>("ModelTutorBooking.FK_tblTutorCourse_tblCourse", "tblCourse", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelTutorBooking", "FK_tblTutorCourse_tblTutor", "tblTutor")]
        public tblTutor tblTutor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblTutor>("ModelTutorBooking.FK_tblTutorCourse_tblTutor", "tblTutor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblTutor>("ModelTutorBooking.FK_tblTutorCourse_tblTutor", "tblTutor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblTutor> tblTutorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblTutor>("ModelTutorBooking.FK_tblTutorCourse_tblTutor", "tblTutor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblTutor>("ModelTutorBooking.FK_tblTutorCourse_tblTutor", "tblTutor", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
